// Status enum
export enum Status {
  Pending = "pending",
  Approved = "approved",
  Rejected = "rejected",
}

// Type for dataset
export type TimeLog = {
  id: number
  date: string
  startTime: string
  endTime: string
  duration: string
  durationMinutes: number
  task: string
  milestone: string
  project: string
  description: string
  user: {
    name: string
    initials: string
    avatar?: string
  }
  billable: boolean
  status: Status
}

// Full dataset (30 entries)
export const timeLogs: TimeLog[] = [
  {
    id: 1,
    date: "2024-01-15",
    startTime: "09:00",
    endTime: "11:30",
    duration: "2h 30m",
    durationMinutes: 150,
    task: "Implement user authentication",
    milestone: "Backend Development",
    project: "E-commerce Platform",
    description:
      "Worked on JWT implementation and user session management. Fixed security vulnerabilities and added proper error handling.",
    user: { name: "Sarah Chen", initials: "SC", avatar: "/professional-woman-diverse.png" },
    billable: true,
    status: Status.Approved,
  },
  {
    id: 2,
    date: "2024-01-15",
    startTime: "14:00",
    endTime: "17:00",
    duration: "3h 00m",
    durationMinutes: 180,
    task: "Design homepage layout",
    milestone: "UI/UX Design",
    project: "Marketing Website",
    description:
      "Created wireframes and mockups for the new homepage design. Collaborated with stakeholders on user flow improvements.",
    user: { name: "Mike Johnson", initials: "MJ", avatar: "/professional-man-developer.png" },
    billable: true,
    status: Status.Pending,
  },
  {
    id: 3,
    date: "2024-01-14",
    startTime: "10:30",
    endTime: "12:00",
    duration: "1h 30m",
    durationMinutes: 90,
    task: "Database optimization",
    milestone: "Performance Improvements",
    project: "E-commerce Platform",
    description: "Optimized database queries and added proper indexing for better performance.",
    user: { name: "Alex Rodriguez", initials: "AR", avatar: "/professional-man-backend.png" },
    billable: true,
    status: Status.Approved,
  },
  {
    id: 4,
    date: "2024-01-14",
    startTime: "15:30",
    endTime: "18:00",
    duration: "2h 30m",
    durationMinutes: 150,
    task: "Mobile responsive design",
    milestone: "Frontend Development",
    project: "Marketing Website",
    description: "Implemented responsive breakpoints and mobile navigation. Tested across multiple devices.",
    user: { name: "Emma Davis", initials: "ED", avatar: "/professional-woman-designer.png" },
    billable: false,
    status: Status.Approved,
  },
  {
    id: 5,
    date: "2024-01-13",
    startTime: "09:15",
    endTime: "11:45",
    duration: "2h 30m",
    durationMinutes: 150,
    task: "API integration testing",
    milestone: "Quality Assurance",
    project: "Mobile App",
    description: "Tested all API endpoints and documented integration issues. Created test automation scripts.",
    user: { name: "Sarah Chen", initials: "SC", avatar: "/professional-woman-diverse.png" },
    billable: true,
    status: Status.Rejected,
  },
  {
    id: 6,
    date: "2024-01-12",
    startTime: "13:00",
    endTime: "16:30",
    duration: "3h 30m",
    durationMinutes: 210,
    task: "Code review and refactoring",
    milestone: "Code Quality",
    project: "E-commerce Platform",
    description: "Reviewed pull requests and refactored legacy code for better maintainability.",
    user: { name: "Alex Rodriguez", initials: "AR", avatar: "/professional-man-backend.png" },
    billable: true,
    status: Status.Approved,
  },
  {
    id: 7,
    date: "2024-01-11",
    startTime: "10:00",
    endTime: "12:30",
    duration: "2h 30m",
    durationMinutes: 150,
    task: "Client meeting and requirements gathering",
    milestone: "Project Planning",
    project: "CRM System",
    description: "Met with client to discuss new feature requirements and project timeline adjustments.",
    user: { name: "Mike Johnson", initials: "MJ", avatar: "/professional-man-developer.png" },
    billable: false,
    status: Status.Approved,
  },
  {
    id: 8,
    date: "2024-01-11",
    startTime: "14:00",
    endTime: "15:45",
    duration: "1h 45m",
    durationMinutes: 105,
    task: "Setup CI/CD pipeline",
    milestone: "DevOps Setup",
    project: "Healthcare Portal",
    description: "Configured GitHub Actions for automated deployments to Kubernetes cluster.",
    user: { name: "Emma Davis", initials: "ED", avatar: "/professional-woman-designer.png" },
    billable: true,
    status: Status.Pending,
  },
  {
    id: 9,
    date: "2024-01-10",
    startTime: "09:00",
    endTime: "12:00",
    duration: "3h 00m",
    durationMinutes: 180,
    task: "Implement payment gateway integration",
    milestone: "Backend Development",
    project: "E-commerce Platform",
    description: "Integrated Stripe payments with error handling and webhook support.",
    user: { name: "Sarah Chen", initials: "SC", avatar: "/professional-woman-diverse.png" },
    billable: true,
    status: Status.Approved,
  },
  {
    id: 10,
    date: "2024-01-09",
    startTime: "10:00",
    endTime: "11:30",
    duration: "1h 30m",
    durationMinutes: 90,
    task: "Bug fixes on order module",
    milestone: "Maintenance",
    project: "E-commerce Platform",
    description: "Resolved issues with order history display and edge-case payment failures.",
    user: { name: "Alex Rodriguez", initials: "AR", avatar: "/professional-man-backend.png" },
    billable: true,
    status: Status.Pending,
  },
  {
    id: 11,
    date: "2024-01-09",
    startTime: "14:00",
    endTime: "16:30",
    duration: "2h 30m",
    durationMinutes: 150,
    task: "Design onboarding flow",
    milestone: "UI/UX Design",
    project: "Mobile App",
    description: "Created wireframes and mockups for mobile onboarding flow.",
    user: { name: "Emma Davis", initials: "ED", avatar: "/professional-woman-designer.png" },
    billable: false,
    status: Status.Rejected,
  },
  {
    id: 12,
    date: "2024-01-08",
    startTime: "09:30",
    endTime: "12:30",
    duration: "3h 00m",
    durationMinutes: 180,
    task: "Write API documentation",
    milestone: "Documentation",
    project: "CRM System",
    description: "Documented API endpoints for user and order modules using OpenAPI.",
    user: { name: "Mike Johnson", initials: "MJ", avatar: "/professional-man-developer.png" },
    billable: true,
    status: Status.Approved,
  },
  {
    id: 13,
    date: "2024-01-08",
    startTime: "13:00",
    endTime: "15:00",
    duration: "2h 00m",
    durationMinutes: 120,
    task: "Implement push notifications",
    milestone: "Mobile Development",
    project: "Mobile App",
    description: "Integrated Firebase Cloud Messaging for real-time notifications.",
    user: { name: "Sarah Chen", initials: "SC", avatar: "/professional-woman-diverse.png" },
    billable: true,
    status: Status.Pending,
  },
  {
    id: 14,
    date: "2024-01-07",
    startTime: "11:00",
    endTime: "13:30",
    duration: "2h 30m",
    durationMinutes: 150,
    task: "User role management",
    milestone: "Backend Development",
    project: "CRM System",
    description: "Added role-based access control with Keycloak integration.",
    user: { name: "Alex Rodriguez", initials: "AR", avatar: "/professional-man-backend.png" },
    billable: true,
    status: Status.Approved,
  },
  {
    id: 15,
    date: "2024-01-07",
    startTime: "15:00",
    endTime: "17:00",
    duration: "2h 00m",
    durationMinutes: 120,
    task: "Accessibility audit",
    milestone: "UI/UX Improvements",
    project: "Marketing Website",
    description: "Audited site for WCAG compliance and fixed color contrast issues.",
    user: { name: "Emma Davis", initials: "ED", avatar: "/professional-woman-designer.png" },
    billable: false,
    status: Status.Rejected,
  },
  // continuing the same style...
  {
    id: 16,
    date: "2024-01-06",
    startTime: "09:00",
    endTime: "11:30",
    duration: "2h 30m",
    durationMinutes: 150,
    task: "Deploy staging environment",
    milestone: "DevOps Setup",
    project: "Healthcare Portal",
    description: "Provisioned staging environment with Docker and Kubernetes.",
    user: { name: "Mike Johnson", initials: "MJ", avatar: "/professional-man-developer.png" },
    billable: true,
    status: Status.Approved,
  },
  {
    id: 17,
    date: "2024-01-06",
    startTime: "13:00",
    endTime: "15:30",
    duration: "2h 30m",
    durationMinutes: 150,
    task: "Implement search feature",
    milestone: "Frontend Development",
    project: "E-commerce Platform",
    description: "Added search functionality with filtering and pagination.",
    user: { name: "Sarah Chen", initials: "SC", avatar: "/professional-woman-diverse.png" },
    billable: true,
    status: Status.Pending,
  },
  {
    id: 18,
    date: "2024-01-05",
    startTime: "10:00",
    endTime: "12:00",
    duration: "2h 00m",
    durationMinutes: 120,
    task: "Load testing",
    milestone: "Quality Assurance",
    project: "Healthcare Portal",
    description: "Conducted load testing with JMeter and identified performance bottlenecks.",
    user: { name: "Alex Rodriguez", initials: "AR", avatar: "/professional-man-backend.png" },
    billable: true,
    status: Status.Approved,
  },
  {
    id: 19,
    date: "2024-01-05",
    startTime: "14:00",
    endTime: "16:00",
    duration: "2h 00m",
    durationMinutes: 120,
    task: "UI consistency review",
    milestone: "UI/UX Improvements",
    project: "Marketing Website",
    description: "Ensured consistent typography and button styles across all pages.",
    user: { name: "Emma Davis", initials: "ED", avatar: "/professional-woman-designer.png" },
    billable: false,
    status: Status.Pending,
  },
  {
    id: 20,
    date: "2024-01-04",
    startTime: "09:00",
    endTime: "10:30",
    duration: "1h 30m",
    durationMinutes: 90,
    task: "Prepare project report",
    milestone: "Project Management",
    project: "CRM System",
    description: "Prepared weekly status report for stakeholders.",
    user: { name: "Mike Johnson", initials: "MJ", avatar: "/professional-man-developer.png" },
    billable: false,
    status: Status.Approved,
  },
  {
    id: 21,
    date: "2024-01-04",
    startTime: "11:00",
    endTime: "13:30",
    duration: "2h 30m",
    durationMinutes: 150,
    task: "Add dark mode",
    milestone: "Frontend Development",
    project: "Mobile App",
    description: "Implemented dark mode toggle and theme persistence.",
    user: { name: "Sarah Chen", initials: "SC", avatar: "/professional-woman-diverse.png" },
    billable: true,
    status: Status.Rejected,
  },
  {
    id: 22,
    date: "2024-01-03",
    startTime: "09:30",
    endTime: "12:00",
    duration: "2h 30m",
    durationMinutes: 150,
    task: "Refactor authentication service",
    milestone: "Code Quality",
    project: "Healthcare Portal",
    description: "Refactored auth service to support multi-factor authentication.",
    user: { name: "Alex Rodriguez", initials: "AR", avatar: "/professional-man-backend.png" },
    billable: true,
    status: Status.Approved,
  },
  {
    id: 23,
    date: "2024-01-03",
    startTime: "14:00",
    endTime: "16:00",
    duration: "2h 00m",
    durationMinutes: 120,
    task: "UI testing",
    milestone: "Quality Assurance",
    project: "CRM System",
    description: "Tested UI flows using Cypress automation scripts.",
    user: { name: "Emma Davis", initials: "ED", avatar: "/professional-woman-designer.png" },
    billable: false,
    status: Status.Pending,
  },
  {
    id: 24,
    date: "2024-01-02",
    startTime: "09:00",
    endTime: "11:00",
    duration: "2h 00m",
    durationMinutes: 120,
    task: "Feature brainstorming",
    milestone: "Project Planning",
    project: "Marketing Website",
    description: "Conducted brainstorming session for upcoming campaign features.",
    user: { name: "Mike Johnson", initials: "MJ", avatar: "/professional-man-developer.png" },
    billable: false,
    status: Status.Rejected,
  },
  {
    id: 25,
    date: "2024-01-02",
    startTime: "13:00",
    endTime: "15:30",
    duration: "2h 30m",
    durationMinutes: 150,
    task: "Localization support",
    milestone: "Frontend Development",
    project: "E-commerce Platform",
    description: "Implemented multi-language support using i18n.",
    user: { name: "Sarah Chen", initials: "SC", avatar: "/professional-woman-diverse.png" },
    billable: true,
    status: Status.Approved,
  },
  {
    id: 26,
    date: "2024-01-01",
    startTime: "10:00",
    endTime: "12:30",
    duration: "2h 30m",
    durationMinutes: 150,
    task: "Security audit",
    milestone: "Security",
    project: "Healthcare Portal",
    description: "Audited app for OWASP vulnerabilities and fixed token leakage issues.",
    user: { name: "Alex Rodriguez", initials: "AR", avatar: "/professional-man-backend.png" },
    billable: true,
    status: Status.Approved,
  },
  {
    id: 27,
    date: "2024-01-01",
    startTime: "14:00",
    endTime: "15:30",
    duration: "1h 30m",
    durationMinutes: 90,
    task: "SEO improvements",
    milestone: "Marketing",
    project: "Marketing Website",
    description: "Improved meta tags, structured data, and page performance for SEO.",
    user: { name: "Emma Davis", initials: "ED", avatar: "/professional-woman-designer.png" },
    billable: false,
    status: Status.Pending,
  },
  {
    id: 28,
    date: "2023-12-31",
    startTime: "09:30",
    endTime: "12:00",
    duration: "2h 30m",
    durationMinutes: 150,
    task: "Implement chat feature",
    milestone: "Backend Development",
    project: "Mobile App",
    description: "Developed real-time chat with WebSockets and message persistence.",
    user: { name: "Sarah Chen", initials: "SC", avatar: "/professional-woman-diverse.png" },
    billable: true,
    status: Status.Rejected,
  },
  {
    id: 29,
    date: "2023-12-30",
    startTime: "10:00",
    endTime: "11:30",
    duration: "1h 30m",
    durationMinutes: 90,
    task: "Data migration",
    milestone: "Maintenance",
    project: "CRM System",
    description: "Migrated legacy customer data into new database schema.",
    user: { name: "Alex Rodriguez", initials: "AR", avatar: "/professional-man-backend.png" },
    billable: true,
    status: Status.Approved,
  }
]
